version: "2"
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"
run:
  timeout: 2m
